[package]
name = "baranyerlikaya/canopus"
version = "0.1.1"
license = "LicenseRef-CC-BY-ND-4.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
description = "Robust distributed lock manager for Roblox featuring autonomous lock renewal and memory-safe architecture."
authors = ["baranyerlikaya"]
include = [
    "default.project.json",
    "src/**",
    "README.md",
    "LICENSE",
    "CONTRIBUTING.md",
]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
