--!strict

local Errors = {
    ERR_TIMEOUT = "ERR_TIMEOUT",
    ERR_MEMORY_STORE_UNAVAILABLE = "ERR_MEMORY_STORE_UNAVAILABLE",
    ERR_INVALID_CONFIG = "ERR_INVALID_CONFIG",
    ERR_LOCK_LOST = "ERR_LOCK_LOST",
    ERR_CONTENDED = "ERR_CONTENDED",
    ERR_NOT_OWNER = "ERR_NOT_OWNER",
}

return Errors
