--!strict
return function()
    local Config = require(game:GetService("ReplicatedStorage").Packages.Canopus.Shared.Config)

    describe("Config", function()
        it("returns defaults when no overrides are given", function()
            local merged = Config.merge(nil)
            expect(merged.leaseDuration).to.equal(30)
            expect(merged.renewalInterval).to.equal(10)
            expect(merged.retryInterval).to.equal(0.5)
            expect(merged.maxRetries).to.equal(0)
            expect(merged.storeName).to.equal("CanopusLocks")
        end)

        it("applies overrides on top of defaults", function()
            local merged = Config.merge({ leaseDuration = 60, storeName = "CustomLocks" })
            expect(merged.leaseDuration).to.equal(60)
            expect(merged.storeName).to.equal("CustomLocks")
            expect(merged.renewalInterval).to.equal(10)
        end)

        it("errors when renewalInterval is not less than half of leaseDuration", function()
            expect(function()
                Config.merge({ leaseDuration = 10, renewalInterval = 6 })
            end).to.throw()
        end)

        it("errors when leaseDuration is zero or negative", function()
            expect(function()
                Config.merge({ leaseDuration = 0 })
            end).to.throw()
        end)

        it("errors when storeName is empty", function()
            expect(function()
                Config.merge({ storeName = "" })
            end).to.throw()
        end)
    end)
end
